# Bootstrap dependencies
FROM public.ecr.aws/docker/library/node:24-alpine AS bootstrap-deps

WORKDIR /bootstrap

RUN npm init -y && \
    npm install --omit=dev @aws-sdk/client-ssm


# Lambda application
FROM public.ecr.aws/docker/library/node:24-alpine

COPY --from=public.ecr.aws/awsguru/aws-lambda-adapter:1.1.0 \
  /lambda-adapter /opt/extensions/lambda-adapter

COPY --from=bootstrap-deps \
  /bootstrap/node_modules \
  /opt/bootstrap/node_modules

ENV PORT=8080
ENV AWS_LWA_PORT=8080
ENV NODE_ENV=production
ENV NODE_PATH=/opt/bootstrap/node_modules

WORKDIR /var/task

COPY app/ ./
COPY bootstrap.js ./

CMD ["node", "bootstrap.js"]
